import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('desktopPet', {
  getState: () => ipcRenderer.invoke('state:get'),
  setPreference: (key, value) => ipcRenderer.invoke('state:setPreference', key, value),
  setMiniEdge: (edge) => ipcRenderer.invoke('state:setMiniEdge', edge),
  updateCharacter: (patch) => ipcRenderer.invoke('character:update', patch),
  setPomodoroConfig: (config) => ipcRenderer.invoke('pomodoro:setConfig', config),
  setPrivacy: (key, value) => ipcRenderer.invoke('privacy:set', key, value),
  triggerEvent: (type) => ipcRenderer.invoke('event:trigger', type),
  refreshWeather: () => ipcRenderer.invoke('weather:refresh'),
  exportCharacterPackage: () => ipcRenderer.invoke('package:exportCharacter'),
  importCharacterPackage: () => ipcRenderer.invoke('package:importCharacter'),
  exportAssetPackage: () => ipcRenderer.invoke('package:exportAssets'),
  importAssetPackage: () => ipcRenderer.invoke('package:importAssets'),
  createTrainingDraft: (text, sourceType) => ipcRenderer.invoke('training:draft', text, sourceType),
  importTrainingFile: () => ipcRenderer.invoke('training:importFile'),
  acceptTrainingDraft: () => ipcRenderer.invoke('training:accept'),
  replaceAsset: (slotId) => ipcRenderer.invoke('asset:replace', slotId),
  selectSpriteReference: () => ipcRenderer.invoke('sprite:selectReference'),
  structureSpriteActions: (config) => ipcRenderer.invoke('sprite:structureActions', config),
  createSpriteRun: (config) => ipcRenderer.invoke('sprite:createRun', config),
  markSpriteJob: (config) => ipcRenderer.invoke('sprite:markJob', config),
  importSpriteJobImage: (config) => ipcRenderer.invoke('sprite:importJobImage', config),
  repairSpriteJob: (config) => ipcRenderer.invoke('sprite:repairJob', config),
  processSpriteRun: (runDir) => ipcRenderer.invoke('sprite:processRun', runDir),
  refreshSpriteRun: (runDir) => ipcRenderer.invoke('sprite:refreshRun', runDir),
  openSpritePath: (kind, runDir) => ipcRenderer.invoke('sprite:openPath', kind, runDir),
  openSpriteJobPath: (config) => ipcRenderer.invoke('sprite:openJobPath', config),
  reviewSpriteRun: (config) => ipcRenderer.invoke('sprite:reviewRun', config),
  applySpriteRun: (runDir) => ipcRenderer.invoke('sprite:applyRun', runDir),
  confirmMemory: (index) => ipcRenderer.invoke('memory:confirm', index),
  deleteMemory: (bucket, index) => ipcRenderer.invoke('memory:delete', bucket, index),
  restoreCharacterVersion: (index) => ipcRenderer.invoke('memory:restoreVersion', index),
  generateHookScripts: () => ipcRenderer.invoke('hooks:generate'),
  scanHookTargets: () => ipcRenderer.invoke('hooks:scanTargets'),
  generateHookSnippets: () => ipcRenderer.invoke('hooks:generateSnippets'),
  installClaudeProjectHook: () => ipcRenderer.invoke('hooks:installClaudeProject'),
  uninstallClaudeProjectHook: () => ipcRenderer.invoke('hooks:uninstallClaudeProject'),
  installHookInstructions: () => ipcRenderer.invoke('hooks:installInstructions'),
  addMemo: (text) => ipcRenderer.invoke('memo:add', text),
  addTimedMemo: (text, dueAt) => ipcRenderer.invoke('memo:addTimed', text, dueAt),
  completeMemo: (id) => ipcRenderer.invoke('memo:complete', id),
  startPomodoro: () => ipcRenderer.invoke('pomodoro:start'),
  pausePomodoro: () => ipcRenderer.invoke('pomodoro:pause'),
  resetPomodoro: () => ipcRenderer.invoke('pomodoro:reset'),
  completePomodoro: () => ipcRenderer.invoke('pomodoro:complete'),
  saveDeepSeek: (config) => ipcRenderer.invoke('deepseek:save', config),
  testDeepSeek: () => ipcRenderer.invoke('deepseek:test'),
  restartAgentBridge: () => ipcRenderer.invoke('agent:restart'),
  showPet: () => ipcRenderer.invoke('window:showPet'),
  onState: (callback) => {
    const handler = (_event, state) => callback(state);
    ipcRenderer.on('state:changed', handler);
    return () => ipcRenderer.removeListener('state:changed', handler);
  }
});
